> 本篇博文是学习的掘金的一篇博文：[【建议星星】要就来45道Promise面试题一次爽到底(1.1w字用心整理)](https://juejin.cn/post/6844904077537574919)，经过自己一个个问题的学习，整理如下：
## 一.Promise的几道基础题
### 题目一
```
const promise1 = new Promise((resolve,reject)=>{
  console.log('promise1')
})
console.log('1',promise1)
// promise1
// 1 Promise {<pending>}
```
> 先执行构造函数中的代码promise1，然后执行同步代码 1，由于没有resolve或者reject，此时状态为pending

### 题目二
```
const promise = new Promise((resolve,reject)=>{
  console.log(1)
  resolve('success')
  console.log(2)
})
promise.then(()=>{
  console.log(3)
})
console.log(4)
// 1 2 4 3
```

### 题目三
```
const promise = new Promise((resolve, reject) => {
  console.log(1);
  console.log(2);
});
promise.then(() => {
  console.log(3);
});
console.log(4);
// 1 2 4
```
> 在promise中没有resolve或者reject，因此promise.then不会执行

### 题目四
```
const promise1 = new Promise((resolve, reject) => {
  console.log('promise1')  // 1 执行构造函数中代码，打印输出
  resolve('resolve1')      // 2 将promise1状态改为resolved，并将结果保存下来
})
const promise2 = promise1.then(res => { // 3. 将这个微任务，放入到微任务队列
  console.log(res)  // 6.执行微任务，打印出结果 resolve1
})
console.log('1', promise1);  //4 打印出promise1的状态为 resolved
console.log('2', promise2);  //5 打印出promise2的状态为 pending，宏任务执行完毕，寻找微任务队列
// promise1
// 1 Promise{<resolved>}
// 2 Promise{<pending>}
// resolve1
```
### 题目五
```
const fn = () => (new Promise((resolve, reject) => {
  console.log(1);
  resolve('success')
}))
fn().then(res => {
  console.log(res)
})
console.log('start')
// 1 
// start
// success
```
> fn是一个函数且直接返回的是一个Promise，主要是因为fn的调用在start之前的，所以先打印出start
### 题目六
```
const fn = () =>
  new Promise((resolve, reject) => {
    console.log(1);
    resolve("success");
  });
console.log("start");
fn().then(res => {
  console.log(res);
});
// start
// 1
// success
```
> 这个fn的调用是在start之后才开始执行的，所以先打印start，再去执行fn这个函数
## 二、Promise结合setTimeout
### 题目七
```
console.log('start')
setTimeout(() => {
  console.log('time')
})
Promise.resolve().then(() => {
  console.log('resolve')
})
console.log('end')
// start
// end
// resolve
// time
```
> 整个脚本作为一个宏任务执行，先打印出start
> setTimeout作为宏任务被放入宏任务队列且下一次宏任务的时候执行  
> Promise.resolve()作为一个微任务，等本轮宏任务执行完毕后，检查微任务队列再执行
> end为本轮宏任务的最后一步，打印出end
> 然后去寻找本次微任务列表，发现Promise.resolve,执行then，打印出resolve
> 进入下一轮宏任务列表，打印出time
### 题目八
```
const promise = new Promise((resolve, reject) => {
  console.log(1);
  setTimeout(() => {
    console.log("timerStart");
    resolve("success"); // 将promise状态改为resolved，且将结果保存在promise.then插入微任务队列
    console.log("timerEnd"); // 会继续执行同步代码
  }, 0);
  console.log(2);
});
promise.then((res) => {
  console.log(res);
});
console.log(4);
// 1
// 2
// 4
// timerStart
// timerEnd
// success
```
### 题目九
```
setTimeout(() => {
  console.log('timer1');
  setTimeout(() => {
    console.log('timer3')
  }, 0)
}, 0)
setTimeout(() => {
  console.log('timer2')
}, 0)
console.log('start')
// start
// timer1
// timer2
// timer3
```
```
setTimeout(() => {
  console.log('timer1');
  Promise.resolve().then(() => {
    console.log('promise')
  })
}, 0)
setTimeout(() => {
  console.log('timer2')
}, 0)
console.log('start')
// start
// timer1
// promise //这里为什么会先执行promise呢？首次看到不应该是先执行完宏任务队列，再去执行微任务队列吗？
// time2
```
> 之所以先打印出promise是因为，第一个setTimeout为下一个宏任务队列，第二个setImeout为下下一个宏任务队列，因此在第二个宏任务队列执行完毕之后，会先去本轮的微任务队列中去查找是否有微任务。
### 题目十
```
Promise.resolve().then(() => {
  console.log('promise1');
  const timer2 = setTimeout(() => {
    console.log('timer2')
  }, 0)
});
const timer1 = setTimeout(() => {
  console.log('timer1')
  Promise.resolve().then(() => {
    console.log('promise2')
  })
}, 0)
console.log('start');
// start
// promise1
// timer1
// promise2
// timer2
```
### 题目十一
```
const promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve('success')
  }, 1000)
})
const promise2 = promise1.then(() => {
  throw new Error('error!!!')
})
console.log('promise1', promise1)
console.log('promise2', promise2)
setTimeout(() => {
  console.log('promise1', promise1)
  console.log('promise2', promise2)
}, 2000)

```
### 题目十二
```
const promise1 = new Promise((resolve, reject) => {
  setTimeout(() => {
    resolve("success");
    console.log("timer1");
  }, 1000);
  console.log("promise1里的内容");
});
const promise2 = promise1.then(() => {
  throw new Error("error!!!");
});
console.log("promise1", promise1);
console.log("promise2", promise2);
setTimeout(() => {
  console.log("timer2");
  console.log("promise1", promise1);
  console.log("promise2", promise2);
}, 2000);
// promise1里的内容
// promise1 Promise{pending}
// promise2 Promise{pending}
// timer1
// throw error
// timer2
// promise1 Promise{resolved}
// promise2 Promise{rejected}
```
## 三、Promise中的then、catch、finally
### 题目十三
```
const promise = new Promise((resolve, reject) => {
  resolve("success1");
  reject("error");
  resolve("success2");
});
promise
.then(res => {
    console.log("then: ", res);
  }).catch(err => {
    console.log("catch: ", err);
  })
// then success1
```
> Promise中的状态一经改变，就不能再次进行改变了。
### 题目十四
```
const promise = new Promise((resolve, reject) => {
  reject("error");
  resolve("success2");
});
promise
.then(res => {
    console.log("then1: ", res);
  }).then(res => {
    console.log("then2: ", res);
  }).catch(err => {
    console.log("catch: ", err);
  }).then(res => {
    console.log("then3: ", res);
  })
// catch error
// then3 undefined
```
> 之所以最后是undefined，是因为之前的那个catch返回的Promise没有返回值
### 题目十五
```
Promise.resolve(1)
  .then(res => {
    console.log(res);
    return 2;
  })
  .catch(err => {
    return 3;
  })
  .then(res => {
    console.log(res);
  });
// 1 2
```
> return 2 会被包装成 Promise(2)
### 题目十六
```
Promise.reject(1)
  .then(res => {
    console.log(res);
    return 2;
  })
  .catch(err => {
    console.log(err);
    return 3
  })
  .then(res => {
    console.log(res);
  });
// 1 3
```
### 题目十七
```
const promise = new Promise((resolve, reject) => {
  setTimeout(() => {
    console.log('timer')
    resolve('success')
  }, 1000)
})
const start = Date.now();
promise.then(res => {
  console.log(res, Date.now() - start)
})
promise.then(res => {
  console.log(res, Date.now() - start)
})
// timer
// success 1000
// success 10001
```
> 这里的.then之所以都会执行，是因为Promise中的.then或者.catch可以被调用多次。
### 题目十八
```
Promise.resolve().then(() => {
  return new Error('error!!!')
}).then(res => {
  console.log("then: ", res)
}).catch(err => {
  console.log("catch: ", err)
})
// then error
```
> 返回任意一个非promise的值都会包裹成promise对象，这里的return new Error('error!!!')被包装成 return Promise.resolve(new Error('error')),如果需要抛出错误，可以使用Promise.reject()或者throw 
### 题目十九
```
const promise = Promise.resolve().then(() => {
  return promise;
})
promise.catch(console.err)
// 结果报错：Uncaught (in promise) TypeError: Chaining cycle detected for promise #<Promise>
```
> Promise的.then或者.catch中返回的值不能是promise本身，否则会造成死循环、报错
### 题目二十
```
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .then(console.log)
// 1
```
> .then或者.catch中的参数期望是函数，如果传入非函数那么就会发生**值穿透**，第一个then和第二个then中传入的都不是函数，因此发生了值的透传，将resolve(1)传入到了最后一个then中。
### 题目二十一
```
Promise.reject('err!!!')
  .then((res) => {
    console.log('success', res)
  }, (err) => {
    console.log('error', err)
  }).catch(err => {
    console.log('catch', err)
  })
// error,err!!!
```
> then函数中会有两个参数，第一个为传入resolve结果的，第二个为reject，可以理解为.catch为.then的简写.then(undeifined,err)
```
Promise.resolve()
  .then(function success (res) {
    throw new Error('error!!!')
  }, function fail1 (err) {
    console.log('fail1', err)
  }).catch(function fail2 (err) {
    console.log('fail2', err)
  })
// fail2 error!
```
### 题目二十一
```
Promise.resolve('1')
  .then(res => {
    console.log(res)
  })
  .finally(() => {
    console.log('finally')
  })
Promise.resolve('2')
  .finally(() => {
    console.log('finally2')
  	return '我是finally2返回的值'
  })
  .then(res => {
    console.log('finally2后面的then函数', res)
  })
// 1
// finally2
// finally
// finally2后面的then函数 2
```
> 为什么finally要在finally2中，看下面代码
```
Promise.resolve('1')
  .finally(() => {
    console.log('finally1')
    throw new Error('我是finally中抛出的异常')
  })
  .then(res => {
    console.log('finally后面的then函数', res)
  })
  .catch(err => {
    console.log('捕获错误', err)
  })
// finally1
// 捕获错误 我是finally中抛出的异常
```
## 四、Promise中的all和race
### 题目二十二-all
```
function runAsync (x) {
    const p = new Promise(r => setTimeout(() => r(x, console.log(x)), 1000))
    return p
}
Promise.all([runAsync(1), runAsync(2), runAsync(3)])
  .then(res => console.log(res))
// 1
// 2
// 3
// [1,2,3]
```
> 有了all，可以并行执行多个异步操作，并且在一个回调中处理所有的返回数据，.all后面的then接收的是所有异步操作的结果。
### 题目二十三-all
```
function runAsync (x) {
  const p = new Promise(r => setTimeout(() => r(x, console.log(x)), 1000))
  return p
}
function runReject (x) {
  const p = new Promise((res, rej) => setTimeout(() => rej(`Error: ${x}`, console.log(x)), 1000 * x))
  return p
}
Promise.all([runAsync(1), runReject(4), runAsync(3), runReject(2)])
  .then(res => console.log(res))
  .catch(err => console.log(err))
// 1
// 3
// 2
// Error 2
// 4
```
### 题目二十四-race
```
function runAsync (x) {
  const p = new Promise(r => setTimeout(() => r(x, console.log(x)), 1000))
  return p
}
Promise.race([runAsync(1), runAsync(2), runAsync(3)])
  .then(res => console.log('result: ', res))
  .catch(err => console.log(err))
// 1
// result 1
// 2
// 3
```
> 虽然race是赛跑且只会获取最先执行的那个结果，但是 2和3还是会去执行的。 
> 应用场景是：为异步请求设置超时时间。
### 题目二十五-race
```
function runAsync(x) {
  const p = new Promise(r =>
    setTimeout(() => r(x, console.log(x)), 1000)
  );
  return p;
}
function runReject(x) {
  const p = new Promise((res, rej) =>
    setTimeout(() => rej(`Error: ${x}`, console.log(x)), 1000 * x)
  );
  return p;
}
Promise.race([runReject(0), runAsync(1), runAsync(2), runAsync(3)])
  .then(res => console.log("result: ", res))
  .catch(err => console.log(err));
// 0
// result :Error:0
// 1
// 2
// 3
```

> all与race小结
> + Promise.all的作用是接收一组异步任务，然后并行执行异步任务，在所有异步任务执行完毕后才执行回调。 
> + Promise.race也是接收一组异步任务，然后并行执行异步任务，只保留第一个先完成的异步执行结果，其它的结果会抛弃不用。  
> + Promise.all.then中的结果与传入到all中的顺序是一致的。 
> + all和race传入的数组如果有抛出异常的错误，那么只会抛出第一个错误。
## 五、async和await
> 在很多时候，async和await的解法和Promise差不多，但是有些又不一样。
### 题目二十六
```
async function async1() {
  console.log("async1 start");
  await async2();
  console.log("async1 end");
}
async function async2() {
  console.log("async2");
}
async1();
console.log('start')
// async1 start
// async2
// start
// async1 end
```
```
async function async1() {
  console.log("async1 start");
  new Promise(resolve => {
    console.log("async2")
    resolve()
  }).then(res => console.log("async1 end"))
}
async function async2() {
  console.log("async2");
}
async1();
console.log("start")
// async1 start
// async2
// start
// async1 end
```
```
async function async1() {
  console.log("async1 start");
  new Promise(resolve => {
    console.log('promise')
  })
  console.log("async1 end");
}
async1();
console.log("start")
// async1 start
// promise
// async1 end
// start
```
### 题目二十七
```
async function async1() {
  console.log("async1 start");
  await async2();
  console.log("async1 end");
}
async function async2() {
  setTimeout(() => {
    console.log('timer')
  }, 0)
  console.log("async2");
}
async1();
console.log("start")
// async1 start
// async2
// async1 end
// start
// timer
```
### 题目二十八
```
async function async1() {
  console.log("async1 start");
  await async2();
  console.log("async1 end");
  setTimeout(() => {  `2`
    console.log('timer1')
  }, 0)
}
async function async2() {
  setTimeout(() => { `1`
    console.log('timer2')
  }, 0)
  console.log("async2");
}
async1();
setTimeout(() => {  `3`
  console.log('timer3')
}, 0)
console.log("start")
// async1 start
// async2
// start
// async1 end
// timer2
// timer1
// timer3
```
### 题目二十九
```
async function fn () {
  // return await 1234
  // 等同于
  return 123
}
fn().then(res => console.log(res))

```
### 题目三十
```
async function async1 () {
  console.log('async1 start');
  await new Promise(resolve => {
    console.log('promise1')
  })
  console.log('async1 success');
  return 'async1 end'
}
console.log('srcipt start')
async1().then(res => console.log(res))
console.log('srcipt end')
// srcipt start
// async1 start
// promise1
// srcipt end
```
### 题目三十一
```
async function async1 () {
  console.log('async1 start');
  await new Promise(resolve => {
    console.log('promise1')
    resolve('promise1 resolve')
  }).then(res => console.log(res))
  console.log('async1 success');
  return 'async1 end'
}
console.log('srcipt start')
async1().then(res => console.log(res))
console.log('srcipt end')
// srcipt start
// async1 start
// promise1
// srcipt end
// promise1 resolve
// async1 success
// async1 end
```
### 题目三十二
```
async function async1 () {
  console.log('async1 start');
  await new Promise(resolve => {
    console.log('promise1')
    resolve('promise resolve')
  })
  console.log('async1 success');
  return 'async1 end'
}
console.log('srcipt start')
async1().then(res => {
  console.log(res)
})
new Promise(resolve => {
  console.log('promise2')
  setTimeout(() => {
    console.log('timer')
  })
})
// srcipt start
// async1 start
// promise1
// promise2
// async1 success
// async1 end
// timer
```
### 题目三十四
```
async function async1() {
  console.log("async1 start");
  await async2();
  console.log("async1 end");
}

async function async2() {
  console.log("async2");
}

console.log("script start");

setTimeout(function() {   //  下一轮宏任务
  console.log("setTimeout");
}, 0);

async1();

new Promise(function(resolve) {
  console.log("promise1");
  resolve();
}).then(function() {
  console.log("promise2");
});
console.log('script end')
// script start
// async1 start
// async2
// promise1
// script end
// async1 end
// promise2
// setTimeout
```
### 题目三十五
```
async function testSometing() {
  console.log("执行testSometing");
  return "testSometing";
}
async function testAsync() {
  console.log("执行testAsync");
  return Promise.resolve("hello async");
}
async function test() {
  console.log("test start...");
  const v1 = await testSometing();
  console.log(v1);
  const v2 = await testAsync();
  console.log(v2);
  console.log(v1, v2);
}
test();
var promise = new Promise(resolve => {
  console.log("promise start...");
  resolve("promise");
});
promise.then(val => console.log(val));
console.log("test end...");
// test start...
// 执行testSometing
// promise start...
// test end...
// testSometing
// 执行testAsync
// promise
// hello async
// testSometing hello async
```
## 六、async处理错误
### 题目三十六
```
async function async1 () {
  await async2();
  console.log('async1');
  return 'async1 success'
}
async function async2 () {
  return new Promise((resolve, reject) => {
    console.log('async2')
    reject('error')
  })
}
async1().then(res => console.log(res))
// async2
// Uncaught (in promise) error
```
> await后面跟着一个rejected的promise，那么就会抛出错误，不再往下执行
```
async function async1 () {
  console.log('async1');
  throw new Error('error!!!')
  return 'async1 success'
}
async1().then(res => console.log(res))
```
> 同上‘
### 题目三十七
```
async function async1 () {
  try {
    await Promise.reject('error!!!')
  } catch(e) {
    console.log(e)
  }
  console.log('async1');
  return Promise.resolve('async1 success')
}
async1().then(res => console.log(res))
console.log('script start')
// script start
// error!!!
// async1
// async1 success
```
```
async function async1 () {
  await Promise.reject('error!!!')
    .catch(e => console.log(e))
  console.log('async1');
  return Promise.resolve('async1 success')
}
async1().then(res => console.log(res))
console.log('script start')
// 同上
```
## 七、综合题
### 题目三十八
```
const first = () => (new Promise((resolve, reject) => {
    console.log(3); // 第一步
    let p = new Promise((resolve, reject) => {
        console.log(7); //第二步
        setTimeout(() => {  //下一个宏任务，往后排
            console.log(5);
            resolve(6);
            console.log(p)
        }, 0)
        resolve(1); //  微任务结果出来了，但是不执行，我保存了1这个结果
    });
    resolve(2); //微任务结果出来了，但是不执行，我保存了2这个结果
    p.then((arg) => { // 接着看，整个代码有没有宏任务执行，一看住代码还有个4没打印，先去打印4
        console.log(arg);
    });
}));
first().then((arg) => {
    console.log(arg);
});
console.log(4);
// 3
// 7
// 4
// 1
// 2
// 5
// Promise{<resolved>: 1}
```
### 题目三十九
```
const async1 = async () => {
  console.log('async1');
  setTimeout(() => {
    console.log('timer1')
  }, 2000)
  await new Promise(resolve => {
    console.log('promise1')
  })
  console.log('async1 end')
  return 'async1 success'
} 

console.log('script start');
async1().then(res => console.log(res));
console.log('script end');
Promise.resolve(1)
  .then(2)
  .then(Promise.resolve(3))
  .catch(4)
  .then(res => console.log(res))
setTimeout(() => {
  console.log('timer2')
}, 1000)
// script start
// async1
// promise1
// script end
// 1 
// timer2
// timer1
```
> 这里需要注意的一点是：async函数中await的new Promise要是没有返回值的话则不执行后面的内容。
### 题目四十
```
const p1 = new Promise((resolve) => {
  setTimeout(() => {
    resolve('resolve3');
    console.log('timer1')
  }, 0)
  resolve('resolve1');
  resolve('resolve2');
}).then(res => {
  console.log(res)
  setTimeout(() => {
    console.log(p1) //p1返回的是finally最终的值，所以也是undefined
  }, 1000)
}).finally(res => {  //finally中是接收不到Promise结果的，这个res是个迷惑项
  console.log('finally', res)
})
// resolve1
// finally,undefined
// timer1
// Promise {resolve:undefined}
```
## 八、大厂面试题
### 题目四十一--使用Promise每秒输入1 2 3
```
const arr = [1, 2, 3]
arr.reduce((p, x) => {
  return p.then(() => {
    return new Promise(r => {
      setTimeout(() => r(console.log(x)), 1000)
    })
  })
}, Promise.resolve())
// 
```
### 题目四十二--使用Promise实现红绿灯交替重复亮
```
// 红灯3秒亮一次，黄灯2秒亮一次，绿灯1秒亮一次
function red {
  console.log('red')
}
function yellow(){
  console.log('yellow')
}
function green(){
  console.log('green')
}
const light = function (timer, cb) {
  return new Promise(resolve => {
    setTimeout(() => {
      cb()
      resolve()
    }, timer)
  })
}
const step = function () {
  Promise.resolve().then(() => {
    return light(3000, red)
  }).then(() => {
    return light(2000, green)
  }).then(() => {
    return light(1000, yellow)
  }).then(() => {
    return step()
  })
}

step();

```
### 题目四十三：封装一个异步加载图片的方法
```
function loadImg(url){
  return new Promise((resolve,reject)=>{
    const img = new Image();
    img.onload = function(){
      console.log('一张图片加载完成')
      resolve(img)
    }
     img.onerror = function() {
    	reject(new Error('Could not load image at' + url));
    };
    img.src = url;
  })
}
```